#!/bin/bash
#SBATCH -J jellyfish
#SBATCH -C "ceph"
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ebriggs@uidaho.edu
#SBATCH -p reg
#SBATCH --mem=180G
#SBATCH --cpus-per-task=12

workdir=/mnt/ceph/hamiltonlab_data/EJB_WGS/APH_5344/
out=/mnt/ceph/hamiltonlab_data/EJB_WGS/APH_5344/analysis/kmer/

#load hifiasm
. /usr/modules/init/bash
module load jellyfish

jellyfish count -F8 <(zcat ${workdir}m64027_230829_115422.hifi_reads.fastq.gz) <(zcat ${workdir}m64027_230830_211805.hifi_reads.fastq.gz) <(zcat ${workdir}m64027_230901_064814.hifi_reads.fastq.gz) <(zcat ${workdir}m64027_230907_225350.hifi_reads.fastq.gz) <(zcat ${workdir}m64027_230909_085557.hifi_reads.fastq.gz) <(zcat ${workdir}m64027_230910_184717.hifi_reads.fastq.gz) <(zcat ${workdir}m64027_230912_053014.hifi_reads.fastq.gz) <(zcat ${workdir}m64027_230913_235829.hifi_reads.fastq.gz) -C -m 31 -s 100M -t 20 -o ${out}APH_5344_8cells.jf ${workdir}m64027_230829_115422.hifi_reads.fastq ${workdir}m64027_230830_211805.hifi_reads.fastq ${workdir}m64027_230901_064814.hifi_reads.fastq ${workdir}m64027_230907_225350.hifi_reads.fastq ${workdir}m64027_230909_085557.hifi_reads.fastq ${workdir}m64027_230910_184717.hifi_reads.fastq ${workdir}m64027_230912_053014.hifi_reads.fastq ${workdir}m64027_230913_235829.hifi_reads.fastq

jellyfish histo ${workdir}/analysis/kmer/APH_5344_8cells.jf > ${out}APH_5344_8cells.histo

#END SCRIPT

#Link to GenomeScope website
Use the same k-mer value as Jellyfish

(http://genomescope.org/)
